name: date_picker_component
version: 1.2.3
author: Marcos Benatti Lauer <benatti77@gmail.com>
description: |-
  A component date picker using pure dart,
  based on polymer version.
homepage: https://github.com/UpLibs/date_picker_component
dependencies:
  intl: '>=0.12.0+1 <0.13.0'
dev_dependencies:
  unittest: any
